# Port TCP classique
listener 1883
protocol mqtt

# Port WebSockets
listener 9001
protocol websockets

# Persistance des données
persistence true
persistence_location /mosquitto/data/

# Sécurité et Authentification
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl